apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: pod
spec:
  containers:
    - name: helm
      image: lachlanevenson/k8s-helm:v3.1.1
      resources:  # limits the resources your build contaienr
        requests:
          memory: "200m"
          cpu: "100m"
        limits:
          memory: "500mi"
          cpu: "200m" 
      command:
        - cat
      tty: true
  volumes:
    - name: m2
      hostPath:
        path: /root/.m2
